baseURL = "https://lepointq.surge.sh"
languageCode = "fr"
title = "Le Point Q"
[params]
	description = "La newsletter qui te plonge dans l’univers du sexe et démystifie l'inconnue nommée &laquo;&nbsp;plaisir&nbsp;&raquo;"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
themes = "themes"
